# Generated by Django 6.0.1 on 2026-02-25 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Importe Estimado')),
                ('is_approved', models.BooleanField(default=False, verbose_name='¿Aprobado?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('dni', models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI/NIE')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Concepto')),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workshop.budget')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plate', models.CharField(max_length=20, verbose_name='Matrícula')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('vin', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bastidor')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='workshop.client', verbose_name='Cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='workshop.vehicle', verbose_name='Vehículo'),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Proceso'), ('FINISHED', 'Terminado'), ('DELIVERED', 'Entregado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('description', models.TextField(verbose_name='Descripción del problema')),
                ('mileage', models.IntegerField(verbose_name='Kilometraje')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Fecha de entrada')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Importe Total')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='workshop.vehicle', verbose_name='Vehículo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Concepto')),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workshop.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Taller')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='workshop_logos/', verbose_name='Logo')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='CIF/NIF')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to=settings.AUTH_USER_MODEL, verbose_name='Dueño')),
            ],
        ),
        migrations.AddField(
            model_name='workorder',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop', verbose_name='Taller'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop', verbose_name='Taller'),
        ),
        migrations.AddField(
            model_name='client',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop', verbose_name='Taller'),
        ),
        migrations.AddField(
            model_name='budget',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop', verbose_name='Taller'),
        ),
    ]
